packages:
  - apps/*
  - packages/*
  - tools/*
  - examples/*

catalogMode: prefer

catalog:
  "@alcalzone/ansi-tokenize": ^0.3.0
  ansi-escapes: ^7.3.0
  "@types/node": ^24.12.4
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: ^0.1.22
  "@vitejs/plugin-vue-jsx": ^5.1.5
  chalk: ^5.6.2
  is-in-ci: ^1.0.0
  patch-console: ^2.0.0
  strip-ansi: ^7.2.0
  node-pty: ^1.0.0
  terminal-size: ^4.0.1
  tsx: ^4.22.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  esbuild: true
  node-pty: true
